### ISSUE TITLE
Example Site

### ISSUE THREAD

**Issue by rmszc81** [JingWangTW/dark-theme-editor#4]
Hello,

First, thank you very much for the great dark-theme-editor hugo theme. it's awesome!

Second, would you kindly provide the sources for your own website that's located at https://jingwangtw.github.io/dark-theme-editor/?

It will be much easier for us to build our own if we have yours as an example.

I'm already using another template for my blog, named hugo-coder, but then, I'd like to use dark-theme-editor for more technical stuff.

Thanks a lot and best regards!
Happy new lunar new year!

**Comment by JingWangTW** [comment]
Hi Rossano,

Thank you for your interest in this theme. It's so great to hear this during the Lunar New Year holiday. I was flattered. 

The source code for the [example site](https://jingwangtw.github.io/dark-theme-editor) is published in the same repository, but in another branch, [`example-site`](https://github.com/JingWangTW/dark-theme-editor/tree/example-site). You should be able to find all the required files there.

I can’t wait to see your blog using this theme. Also, I'd be happy to hear any suggestions or comments from users after applying the template. 

Thank you.

**Comment by rmszc81** [comment]
@JingWangTW I'll have a look as soon as I can into this my friend.

About the New Year Holiday, I'm living in Vietnam since 2016 so, I'm also enjoying these days, hehehehe.

And then, it's me who should say Thank you. Many thanks for sharing this template with the community!

Be seeing ya.
