### ISSUE TITLE
config.toml does not exist

### ISSUE THREAD

**Issue by nilgaar** [JingWangTW/dark-theme-editor#7]
The file config.toml is referred in the readme, but does not exist in the project.
https://github.com/JingWangTW/dark-theme-editor/blob/main/config.toml

**Comment by JingWangTW** [comment]
Hello. Thank you for reporting the issue. The actual example config file is [`hugo.toml`](https://github.com/JingWangTW/dark-theme-editor/blob/main/hugo.toml). The readme may have some misleading errors, and I will update it ASAP.
